# Configuration parameters for main_with_raspi.py
raspi: False
vis: True
token: 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI4NjBkOTdhOGY1NmM0OTY5OGVkMDZkYjg4Y2Q1ZjBmZiIsImlhdCI6MTY0NTg5NTY2MiwiZXhwIjoxOTYxMjU1NjYyfQ.L7mvKMyrRcGADZD3-SFb8-USg8HywbHy_Cq32tUy0NQ'
raspi_ip: 192.168.0.31
raspi_port: 8123